### ISSUE TITLE
Versão v1.22.2 sem os arquivos de CSS

### ISSUE THREAD

**Issue by rubinhos** [totvs/portinari-theme-totvs#17]
A versão v1.22.2 está sem os arquivos CSS ocorrendo erro ao subir a aplicação Angular pela falta do arquivo node_modules/@totvs/portinari-theme/css/po-theme-default.min.css.

Na versão 1.22.1 não ocorre o problema.

**Comment by jhosefmarks** [comment]
Novo patch liberado, favor instalar a versão do pacote 1.22.3.

IMPORTANTE: apenas o pacote do tema foi atualizado, o mesmo é compatível com a versão 1.22.2 do Portinari UI.

**Comment by rubinhos** [comment]
Obrigado Jhosef!
